"""Unified database access for Malaysia Linguistics Lab.

Production (Render): set DATABASE_URL → PostgreSQL via psycopg.
Local development: leave DATABASE_URL unset → SQLite file via db_path.

Application SQL may keep ``?`` placeholders; this module rewrites them for
PostgreSQL. Never log DATABASE_URL or credentials.
"""

from __future__ import annotations

import os
import re
import sqlite3
import threading
from contextlib import contextmanager
from typing import Any, Iterable, Optional, Sequence

from db_path import resolve_database_path

_dialect: Optional[str] = None
_pg_module = None
_sqlite_path: Optional[str] = None
_startup_lock = threading.Lock()


def _normalize_database_url(url: str) -> str:
    """Render often provides postgres://; psycopg expects postgresql://."""
    if url.startswith("postgres://"):
        return "postgresql://" + url[len("postgres://") :]
    return url


def get_database_url() -> Optional[str]:
    raw = (os.environ.get("DATABASE_URL") or "").strip()
    if not raw:
        return None
    return _normalize_database_url(raw)


def is_postgres() -> bool:
    return get_database_url() is not None


def get_dialect() -> str:
    global _dialect
    if _dialect is None:
        _dialect = "postgres" if is_postgres() else "sqlite"
    return _dialect


def get_sqlite_path(fallback_dir: Optional[str] = None) -> str:
    global _sqlite_path
    if _sqlite_path is None:
        _sqlite_path = resolve_database_path(fallback_dir)
    return _sqlite_path


def set_sqlite_path(path: str) -> None:
    """Align SQLite path after Flask app.root_path is known (local only)."""
    global _sqlite_path
    _sqlite_path = os.path.abspath(path)


def sql_pk_column(name: str = "id") -> str:
    """Dialect-specific auto-increment primary key column DDL fragment."""
    if get_dialect() == "postgres":
        return f"{name} INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return f"{name} INTEGER PRIMARY KEY AUTOINCREMENT"


def sql_epoch_now() -> str:
    """SQL expression evaluating to unix epoch seconds (integer/bigint)."""
    if get_dialect() == "postgres":
        return "CAST(EXTRACT(EPOCH FROM NOW()) AS BIGINT)"
    return "strftime('%s','now')"


def render_ddl(sql: str) -> str:
    """Rewrite portable DDL/DML fragments for the active dialect."""
    out = sql
    if get_dialect() == "postgres":
        out = re.sub(
            r"\bid\s+INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b",
            "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            out,
            flags=re.IGNORECASE,
        )
        epoch = sql_epoch_now()
        out = out.replace(
            "DEFAULT (strftime('%s','now'))",
            f"DEFAULT ({epoch})",
        )
        out = out.replace("strftime('%s','now')", epoch)
    return out


def adapt_sql(sql: str) -> str:
    """Rewrite SQLite-oriented SQL for the active dialect."""
    out = render_ddl(sql)
    if get_dialect() != "postgres":
        return out

    # INSERT OR IGNORE → ON CONFLICT DO NOTHING (append if not already present)
    if re.search(r"(?i)\bINSERT\s+OR\s+IGNORE\s+INTO\b", out):
        out = re.sub(
            r"(?i)\bINSERT\s+OR\s+IGNORE\s+INTO\b",
            "INSERT INTO",
            out,
            count=1,
        )
        if not re.search(r"(?i)\bON\s+CONFLICT\b", out):
            out = out.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"

    # ON CONFLICT(cols) → ON CONFLICT (cols)
    out = re.sub(
        r"(?i)\bON\s+CONFLICT\s*\(",
        "ON CONFLICT (",
        out,
    )

    # excluded.col → EXCLUDED.col (PostgreSQL conflict pseudo-table)
    out = re.sub(r"(?i)\bexcluded\.", "EXCLUDED.", out)

    # SQLite RANDOM() → PostgreSQL random()
    out = re.sub(r"(?i)\bRANDOM\s*\(\s*\)", "random()", out)

    # Bind markers ? → %s (application SQL uses ? only as placeholders)
    out = out.replace("?", "%s")
    return out


def row_value(row: Any, *names: str, index: Optional[int] = None) -> Any:
    """Read a column from SQLite Row or PostgreSQL dict_row safely.

    Prefer named columns. Fall back to positional index only for sequence-like
    rows (sqlite3.Row / tuple). Never use ``row[0]`` on dict rows — that raises
    ``KeyError: 0`` under psycopg ``dict_row``.
    """
    if row is None:
        return None

    if isinstance(row, dict):
        for name in names:
            if name in row:
                return row[name]
        lower_map = {str(k).lower(): v for k, v in row.items()}
        for name in names:
            if name.lower() in lower_map:
                return lower_map[name.lower()]
        if index is not None:
            values = list(row.values())
            if 0 <= index < len(values):
                return values[index]
        return None

    for name in names:
        try:
            return row[name]
        except (KeyError, IndexError, TypeError):
            continue

    if index is not None:
        try:
            return row[index]
        except (KeyError, IndexError, TypeError):
            return None
    return None


def row_to_dict(row: Any) -> dict:
    """Normalize a DB row to a plain dict (SQLite Row or PG dict_row)."""
    if row is None:
        return {}
    if isinstance(row, dict):
        return dict(row)
    try:
        return dict(row)
    except Exception:
        if hasattr(row, "keys"):
            return {k: row[k] for k in row.keys()}
        return {str(i): v for i, v in enumerate(row)}


class _CursorProxy:
    """Thin cursor wrapper with lastrowid helper for both backends."""

    def __init__(self, cursor: Any, dialect: str, last_id: Any = None):
        self._cursor = cursor
        self._dialect = dialect
        self._last_id = last_id

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()

    def fetchmany(self, size: Optional[int] = None):
        if size is None:
            return self._cursor.fetchmany()
        return self._cursor.fetchmany(size)

    @property
    def lastrowid(self):
        if self._last_id is not None:
            return self._last_id
        return getattr(self._cursor, "lastrowid", None)

    def __iter__(self):
        return iter(self._cursor)


class DbConnection:
    """Connection facade mimicking sqlite3.Connection.execute / commit / close."""

    def __init__(self, raw: Any, dialect: str):
        self._raw = raw
        self.dialect = dialect

    def execute(self, sql: str, params: Optional[Sequence[Any]] = None):
        adapted = adapt_sql(sql)
        # Auto-RETURNING id for plain INSERTs when caller needs lastrowid (PG).
        wants_id = False
        if (
            self.dialect == "postgres"
            and re.match(r"(?is)^\s*INSERT\s+INTO\b", adapted)
            and not re.search(r"(?i)\bRETURNING\b", adapted)
            and not re.search(r"(?i)\bON\s+CONFLICT\b", adapted)
        ):
            # Only add RETURNING when table has an id column pattern — safe default
            # for this app's INSERT ... VALUES used with lastrowid.
            if re.search(
                r"(?is)INSERT\s+INTO\s+(users|quiz_session_history)\b",
                adapted,
            ):
                adapted = adapted.rstrip().rstrip(";") + " RETURNING id"
                wants_id = True

        if self.dialect == "postgres":
            if params is None:
                cur = self._raw.execute(adapted)
            else:
                cur = self._raw.execute(adapted, tuple(params))
            last_id = None
            if wants_id:
                row = cur.fetchone()
                if row is not None:
                    last_id = row_value(row, "id", index=0)
            return _CursorProxy(cur, self.dialect, last_id)

        if params is None:
            cur = self._raw.execute(adapted)
        else:
            cur = self._raw.execute(adapted, params)
        return _CursorProxy(cur, self.dialect)

    def executescript(self, script: str) -> None:
        """Run multiple statements (SQLite executescript / PG split execute)."""
        if self.dialect == "sqlite":
            self._raw.executescript(adapt_sql(script))
            return
        # Strip comments lightly and split on semicolons.
        cleaned = re.sub(r"--[^\n]*", "", script)
        for part in cleaned.split(";"):
            stmt = part.strip()
            if stmt:
                self.execute(stmt)

    def commit(self) -> None:
        self._raw.commit()

    def rollback(self) -> None:
        self._raw.rollback()

    def close(self) -> None:
        self._raw.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        if exc_type is not None:
            try:
                self.rollback()
            except Exception:
                pass
        self.close()
        return False


def get_db() -> DbConnection:
    """Open a new DB connection (caller commits/closes)."""
    dialect = get_dialect()
    if dialect == "postgres":
        global _pg_module
        if _pg_module is None:
            import psycopg
            from psycopg.rows import dict_row

            _pg_module = (psycopg, dict_row)
        psycopg, dict_row = _pg_module
        url = get_database_url()
        if not url:
            raise RuntimeError("DATABASE_URL is not set")
        raw = psycopg.connect(url, row_factory=dict_row)
        return DbConnection(raw, "postgres")

    path = get_sqlite_path()
    raw = sqlite3.connect(path, timeout=60)
    raw.row_factory = sqlite3.Row
    raw.execute("PRAGMA foreign_keys = ON")
    try:
        raw.execute("PRAGMA journal_mode=WAL")
    except sqlite3.Error:
        pass
    return DbConnection(raw, "sqlite")


def table_columns(conn: DbConnection, table: str) -> set[str]:
    """Return lowercase column names for a table (portable)."""
    if conn.dialect == "postgres":
        rows = conn.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = ?
            """,
            (table.lower(),),
        ).fetchall()
        names = set()
        for row in rows:
            val = row_value(row, "column_name", index=0)
            if val is not None:
                names.add(str(val).lower())
        return names

    rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
    names = set()
    for row in rows:
        # sqlite3.Row: index 1 is name (cid, name, type, ...)
        val = row_value(row, "name", index=1)
        if val is not None:
            names.add(str(val).lower())
    return names


def ensure_column(
    conn: DbConnection,
    table: str,
    column: str,
    ddl_type_and_default: str,
) -> None:
    """ADD COLUMN if missing. ddl_type_and_default like \"TEXT DEFAULT 'local'\"."""
    cols = table_columns(conn, table)
    if column.lower() in cols:
        return
    conn.execute(
        f"ALTER TABLE {table} ADD COLUMN {column} {ddl_type_and_default}"
    )


@contextmanager
def startup_lock():
    """Serialize schema/seed across threads; Postgres also uses advisory lock."""
    with _startup_lock:
        conn = None
        locked = False
        try:
            if is_postgres():
                conn = get_db()
                conn.execute("SELECT pg_advisory_lock(?)", (87236401,))
                locked = True
            yield
        finally:
            if locked and conn is not None:
                try:
                    conn.execute("SELECT pg_advisory_unlock(?)", (87236401,))
                    conn.commit()
                except Exception:
                    pass
                try:
                    conn.close()
                except Exception:
                    pass


def describe_backend() -> str:
    """Safe one-line backend description for startup logs (no secrets)."""
    if is_postgres():
        return "PostgreSQL (DATABASE_URL)"
    return f"SQLite ({get_sqlite_path()})"
